apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-helmrelease-monitor
  namespace: cluster-config
spec:
  targetNamespace: monitor
  releaseName: prometheus
  interval: 5m
     
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: cluster-config
      interval: 1m
      install:
        remediation:
        retries: 3
