apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flux-system-clusterrole-custom
rules: 

- apiGroups: ["helm.toolkit.fluxcd.io"]
  resources: ["*" ]
  verbs: ["*"]
- apiGroups: ["source.toolkit.fluxcd.io"]
  resources: ["*" ]
  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*" ]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["*" ]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*" ]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-system-clusterrolebinding-flyx-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-system-helmreleases
subjects:
- kind: ServiceAccount
  name: flux-applier
  namespace: flux-system
