apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-helmrelease
  namespace: monitor
spec:
  targetNamespace: monitor
  releaseName: prometheus
  interval: 5m
     
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitor
      interval: 1m
