apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- simple-api.yml
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: simple-api
    path: patch-namespaces.yml
  - target:
      version: v1
      kind: Service
      name: simple-api
    path: patch-namespaces.yml
