apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- simple-api.yml
patchesJson6902:
  - path: |
      - op: replace
        path: /metadata/namespace
        value: dev-team-1
    target:
      group: apps
      version: v1
      kind: Deployment
      name: simple-api
  - path: |
      - op: replace
        path: /metadata/namespace
        value: dev-team-1
    target:
      version: v1
      kind: Service
      name: simple-api