apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
  namespace: dev-team-1
  labels:
    version: $(IMAGE_VERSION)

spec:
  replicas: 3  
  template:    
    spec:
      containers:
      - name: api
        image: gperezivo/simple-api:$(IMAGE_VERSION)
