apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-system-helmreleases-monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-system-helmreleases
subjects:
- kind: ServiceAccount
  name: flux-applier
  namespace: monitor
