name: publish_auto_pr
on:
  push:
    branches: 
      - main
    paths:
      - apps/simple-api/**
  workflow_dispatch:
  

jobs:
  publish: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          IMAGE_VERSION=$(cat apps/simple-api/version.properties)
          echo "IMAGE_VERSION=$IMAGE_VERSION" >> $GITHUB_ENV
          eval "echo \"$(cat apps/simple-api/overlays/dev/simple-api-template.yml)\"" > apps/simple-api/overlays/dev/simple-api.yml
          cat apps/simple-api/overlays/dev/simple-api.yml
      - name: 'Kustomize Build simple-api'
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: '3.0.0'
          kustomize_build_dir: 'apps/simple-api/overlays/dev'
          kustomize_comment: true
          kustomize_output_file: "kind-arc-cicd-cluster/dev-team-1/simple-api.yaml"
          kustomize_build_options: "--load_restrictor none"
          enable_alpha_plugins: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

      
  
